change_options:
  name: Change Options
  description: Changes a option.
  fields:
    device_name:
      description: Name of the home appliance.
      example: "Oven Simulator"
    key:
      description: Option key.
      example: "Cooking.Oven.Option.SetpointTemperature"
    value:
      description: Value of the option.
      example: 230
